# DENSO Tetris Configuration File (Updated for Neon Database)

# Screen settings - Optimized for 14" notebook
screen:
  width: 720
  height: 680
  fullscreen: false
  vsync: true
  target_fps: 60

# Game settings
game:
  difficulty: medium # easy, medium, hard
  start_level: 1
  max_level: 20
  level_up_lines: 10 # lines required to level up
  das_delay: 170 # Delayed Auto Shift (milliseconds)
  arr_delay: 30 # Auto Repeat Rate (milliseconds)
  gravity_table: # falling speed of blocks per level (frames per cell)
    1: 60
    2: 50
    3: 40
    4: 30
    5: 25
    6: 20
    7: 15
    8: 12
    9: 10
    10: 8
    11: 7
    12: 6
    13: 5
    14: 4
    15: 3
    16: 3
    17: 2
    18: 2
    19: 1
    20: 1

# Block settings
tetromino:
  ghost_piece: true # show ghost piece at bottom
  enable_hold: true # enable hold feature
  enable_preview: true # enable next block preview
  preview_count: 3 # number of blocks to show in preview
  spin_bonus: true # bonus for special spins

# Graphics settings - Elegant minimalist theme
graphics:
  theme: 'denso' # default, denso, retro, minimalist
  particles: true # enable particle effects
  animations: true # enable animations
  shaders: true # enable shader effects
  bloom_effect: true # enable bloom effect
  shake_effect: true # enable shake effect
  trail_effect: false # trail effect disabled for cleaner look

# Audio settings
audio:
  music_volume: 0.6
  sfx_volume: 0.7
  enable_music: true
  enable_sfx: true

# Control settings
controls:
  keyboard:
    move_left: [K_LEFT, K_a]
    move_right: [K_RIGHT, K_d]
    soft_drop: [K_DOWN, K_s]
    hard_drop: [K_SPACE]
    rotate_cw: [K_UP, K_x]
    rotate_ccw: [K_z, K_LCTRL]
    hold: [K_c, K_LSHIFT]
    pause: [K_p, K_ESCAPE]

  joystick:
    enabled: true
    move_left: 0 # axis or button value
    move_right: 1
    soft_drop: 2
    hard_drop: 3
    rotate_cw: 4
    rotate_ccw: 5
    hold: 6
    pause: 7

# Database settings - Updated for Neon PostgreSQL
database:
  engine: 'postgresql' # postgresql, sqlite (fallback)

  # Neon PostgreSQL Configuration (Primary)
  postgresql:
    # Connection will be loaded from DATABASE_URL environment variable
    # Format: postgres://user:password@host:port/database?sslmode=require
    url: '${DATABASE_URL}'
    pool_size: 10
    max_overflow: 20
    pool_timeout: 30
    pool_recycle: 3600
    echo: false # Set to true for SQL debugging
    ssl_mode: 'require'
    connect_timeout: 10
    command_timeout: 30

  # Fallback SQLite Configuration (for development/offline mode)
  sqlite:
    path: './tetris.db'
    pool_timeout: 20

  # Connection retry settings
  retry:
    max_attempts: 3
    delay_seconds: 1
    backoff_multiplier: 2

# UI settings - Optimized for 14" notebook
ui:
  font: 'arial' # font name
  language: 'en' # en
  show_fps: true
  show_ghost_piece: true
  show_grid: true
  show_next_pieces: true
  menu_animations: true
  button_style: 'minimal' # minimal, rounded, classic
  color_scheme: 'dark' # dark, light

# Achievement system
achievements:
  enabled: true
  notifications: true
  cloud_sync: true # Sync achievements to database

# Logging configuration
logging:
  level: 'INFO' # DEBUG, INFO, WARNING, ERROR, CRITICAL
  console_output: true
  file_output: true
  max_file_size_mb: 10
  backup_count: 5
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

# Security settings
security:
  password_min_length: 6
  session_timeout_minutes: 30
  max_login_attempts: 5
  lockout_duration_minutes: 15
  bcrypt_rounds: 12

# Performance settings
performance:
  cache_enabled: true
  cache_ttl_seconds: 300
  batch_size: 100
  connection_pool_pre_ping: true
  query_timeout_seconds: 30
