# Modern Tetris Configuration File

# ตั้งค่าหน้าจอ
screen:
  width: 800
  height: 800
  fullscreen: false
  vsync: true
  target_fps: 60

# ตั้งค่าเกม
game:
  difficulty: medium # easy, medium, hard
  start_level: 1
  max_level: 20
  level_up_lines: 10 # จำนวนแถวที่ต้องทำลายเพื่อเลื่อนระดับ
  das_delay: 170 # Delayed Auto Shift (milliseconds)
  arr_delay: 30 # Auto Repeat Rate (milliseconds)
  gravity_table: # ความเร็วตกของบล็อคในแต่ละระดับ (frames per cell)
    1: 60
    2: 50
    3: 40
    4: 30
    5: 25
    6: 20
    7: 15
    8: 12
    9: 10
    10: 8
    11: 7
    12: 6
    13: 5
    14: 4
    15: 3
    16: 3
    17: 2
    18: 2
    19: 1
    20: 1

# ตั้งค่าบล็อก
tetromino:
  ghost_piece: true # แสดงเงาบล็อกด้านล่าง
  enable_hold: true # เปิดใช้งานการเก็บบล็อก
  enable_preview: true # เปิดใช้งานการแสดงบล็อกถัดไป
  preview_count: 5 # จำนวนบล็อกที่แสดงในตัวอย่าง
  spin_bonus: true # โบนัสสำหรับการหมุนพิเศษ

# ตั้งค่ากราฟิก
graphics:
  theme: 'neon' # default, neon, retro, minimalist
  particles: true # เปิดใช้งานเอฟเฟกต์อนุภาค
  animations: true # เปิดใช้งานแอนิเมชัน
  shaders: true # เปิดใช้งาน shader effects
  bloom_effect: true # เปิดใช้งานเอฟเฟกต์บลูม (เรืองแสง)
  shake_effect: true # เปิดใช้งานเอฟเฟกต์สั่น
  trail_effect: true # เอฟเฟกต์ทิ้งร่องรอย

# ตั้งค่าเสียง
audio:
  music_volume: 0.7
  sfx_volume: 0.8
  enable_music: true
  enable_sfx: true

# ตั้งค่าการควบคุม
controls:
  keyboard:
    move_left: [K_LEFT, K_a]
    move_right: [K_RIGHT, K_d]
    soft_drop: [K_DOWN, K_s]
    hard_drop: [K_SPACE]
    rotate_cw: [K_UP, K_x]
    rotate_ccw: [K_z, K_LCTRL]
    hold: [K_c, K_LSHIFT]
    pause: [K_p, K_ESCAPE]

  joystick:
    enabled: true
    move_left: 0 # ค่า axis หรือปุ่ม
    move_right: 1
    soft_drop: 2
    hard_drop: 3
    rotate_cw: 4
    rotate_ccw: 5
    hold: 6
    pause: 7

# ตั้งค่าฐานข้อมูล
database:
  engine: 'sqlite' # sqlite, mysql, postgresql
  sqlite:
    path: './tetris.db'
  mysql:
    host: 'localhost'
    port: 3306
    user: 'tetris_user'
    password: 'tetris_password'
    database: 'tetris_db'
  postgresql:
    host: 'localhost'
    port: 5432
    user: 'tetris_user'
    password: 'tetris_password'
    database: 'tetris_db'

# ตั้งค่า UI
ui:
  font: 'Kanit' # ชื่อฟอนต์
  language: 'th' # th, en
  show_fps: true
  show_ghost_piece: true
  show_grid: true
  show_next_pieces: true
  menu_animations: true

# ตั้งค่าระบบรางวัล
achievements:
  enabled: true
  notifications: true
